feat: add `remoteDetectionAlert` doc type
digidem/comapeo-schema pull request #234
Opened 2024-09-02 17:28 UTC by tomasciccola

This adds the `remoteDetectionAlert` doc type. The `geometry` message is a stub for now, until @gmaclennan implements its decoding conversion to GeoJSON.

The only doubt I have is around `sourceId`. Is there a clear format for this string? Should we add concrete validation for it?

2024-09-04 14:02 UTC, gmaclennan commented
This depends on #248 (because @comapeo/geometry doesn't export `fromPartial` methods, and it's easier to remove them from here than try to write then for Geometry), so that should be merged first.

The actual changes to add geometry are in https://github.com/digidem/mapeo-schema/pull/234/commits/7733276587d1d57109e502e635f914a7c9a896cc

It is a bit more complicated than I would like because of the need to deal with JSONSchema refs with 3 different libraries that we use (`ajv`, `@json-schema-tools/dereferencer` and `@apidevtools/json-schema-ref-parser`).

Would be nice to replace `@json-schema-tools/dereferencer` with `@apidevtools/json-schema-ref-parser` at some point, because the latter is already a dep of `json-schema-to-typescript` and we need to deal with it for that.

2024-09-04 14:13 UTC, EvanHahn commented
I plan to review this next week.

2024-09-08 14:10 UTC, EvanHahn requested changes
I assume you and Gregor decided that this was a good format for alerts.

There's a bunch of Observation stuff in here that needs to be reverted. I _think_ merging `main` should fix that.

Otherwise mostly LGTM.

2024-09-08 14:10 UTC, EvanHahn commented on schema/remoteDetectionAlert/v1.json
> +    "detectionDateEnd",
Intuitively I don't know if this should be required. What if there's an alert that's still active?

2024-09-09 09:09 UTC, gmaclennan commented on src/lib/decode-conversions.ts
> +  }
This value is coming from the ts-proto decoder, which will [always decode this to a valid ISO date string](https://github.com/stephenh/ts-proto/blob/main/src/main.ts#L974), even if the value is the default UNIX zero date.

2024-09-09 09:11 UTC, gmaclennan commented on proto/geometry/v1.proto
Resolved in https://github.com/digidem/mapeo-schema/pull/234/commits/11fbc82c89437d9dfe2fff2a5700848bb97760fc

2024-09-09 09:11 UTC, gmaclennan commented on proto/observation/v1.proto
Resolved in merge https://github.com/digidem/mapeo-schema/pull/234/commits/512d4e92151624954b5bb6b1bb7b1eb2360dd337

2024-09-09 09:11 UTC, gmaclennan commented on src/lib/decode-conversions.ts
> +  const { common, metadata, schemaVersion, ...rest } = message
Resolved in merge https://github.com/digidem/mapeo-schema/pull/234/commits/512d4e92151624954b5bb6b1bb7b1eb2360dd337

2024-09-09 09:12 UTC, gmaclennan commented on src/lib/decode-conversions.ts
> +}
Resolved in merge https://github.com/digidem/mapeo-schema/pull/234/commits/512d4e92151624954b5bb6b1bb7b1eb2360dd337

2024-09-09 09:12 UTC, gmaclennan commented on test/index.test.js
> +
Resolved in merge https://github.com/digidem/mapeo-schema/pull/234/commits/512d4e92151624954b5bb6b1bb7b1eb2360dd337

2024-09-09 09:12 UTC, gmaclennan commented on src/lib/encode-conversions.ts
> -  }
Reserved in merge https://github.com/digidem/mapeo-schema/pull/234/commits/512d4e92151624954b5bb6b1bb7b1eb2360dd337

2024-09-09 09:13 UTC, gmaclennan approved these changes
I think I've resolved all of Evan's comments and I've re-reviewed this, and it looks good to merge to me. @EvanHahn this needs a review approval from you to merge.

2024-09-09 13:40 UTC, gmaclennan requested changes
I think we should not merge this until we have released the MVP, in case we need bug fixes before MVP (having this merged would complicate bug fixes)

2024-09-09 14:03 UTC, tomasciccola commented
> I think we should not merge this until we have released the MVP, in case we need bug fixes before MVP (having this merged would complicate bug fixes)

wouldn't it make sense to have a 'develop' branch where we merge this so we don't have a bunch of dangling open PRs (but maybe there won't be many of this)?

2024-09-30 14:18 UTC, EvanHahn approved these changes
LGTM other than one small nitpick.

2024-09-30 14:18 UTC, EvanHahn commented on proto/remoteDetectionAlert/v1.proto
> +  google.protobuf.Timestamp detectionDateEnd = 3;
Could we add `[(required) = true]` to these?

```suggestion
  google.protobuf.Timestamp detectionDateStart = 2 [(required) = true];
  google.protobuf.Timestamp detectionDateEnd = 3 [(required) = true];
```

2024-09-30 14:24 UTC, merged